spring:
  output:
    ansi:
      enabled: always

  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/ecommerce
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 500

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/manage"
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: "full"
  server:
    port: 9292
info:
  app:
    name: hello-actuator
    company: cj

